backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: "src/images" # Media files will be stored in the repo under src/images
public_folder: "static"

collections:
  - name: "fotos" # Used in routes, e.g., /admin/collections/blog
    label: "Fotos" # Used in the UI
    create: false
    folder: "data/pages"
    filter:
      field: "type"
      value: "images"
    fields:
      - {name: "type", widget: hidden}
      - {name: "page", widget: hidden}
      - {laber: "Obs: Não faça o upload de imagens maiores que 8mb, use um otimizador de imagens se preciso (ex: http://www.imagesmaller.com/)", name: "instruções", widget: boolean, }
      - label: "Imagens"
        name: "images"
        widget: "list"
        required: true
        fields:
          - {label: "Título (não aparece no site)", name: "title", widget: "string"}
          - {label: "Imagem selecionada", name: "img", widget: "image", required: true}
          - {label: "Destaque", name: "featured", widget: "boolean", default: false, required: true}
          - {label: "Descrição (opcional)", name: "description", widget: "text"}
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Páginas do site" # Used in the UI
    create: false
    files:
      - label: "Sobre"
        name: "sobre"
        file: "data/pages/Sobre.md"
        fields:
          - {name: "page", widget: hidden}
          - {name: "title", widget: hidden}
          - {label: "Imagem da capa", name: "heroImg", widget: "image", required: true}
          - {label: "Texto", name: "content", widget: "text", required: true}
      - label: "Contato"
        name: "contact"
        file: "data/pages/Contato.md"
        fields:
          - {name: "page", widget: hidden}
          - {label: "Imagem da capa", name: "heroImg", widget: "image", required: true}
          - {label: "Telefone", name: "phone", widget: "string", required: true}
          - {label: "Email", name: "email", widget: "string", required: true}
          - {label: "Endereço (use <br> para a quebra de linha)", name: "address", widget: "text", required: true}
          - {label: "Link para o instagram (opcional)", name: "instagramLink", widget: "string"}
          - {label: "Link para o facebook (opcional)", name: "facebookLink", widget: "string"}
          - {label: "Whatsapp (opcional)", name: "whatsapp", widget: "string"}
