backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "src/images" # Media files will be stored in the repo under src/images
public_folder: "static"

collections:
  - name: "fotos" # Used in routes, e.g., /admin/collections/blog
    label: "Fotos" # Used in the UI
    create: false
    folder: "data/pages"
    filter:
      field: type
      value: images
    fields:
    - {name: "type", widget: hidden}
    - {name: "page", widget: hidden}
    - label: "Imagens"
      name: "gallery"
      widget: "list"
      required: true
      field:
        - {label: "Título (não aparece no site)", name: "title", widget: "string"}
        - {label: "Imagem", name: "img", widget: "image", required: true}
        - {label: "Destaque", name: "featured", widget: "boolean", default: false, required: true}
        - {label: "Descrição (opcional)", name: "description", widget: "text"}
