backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/img" # Media files will be stored in the repo under static/img
public_folder: "img"

collections:
  - name: "projetos" # Used in routes, e.g., /admin/collections/blog
    label: "Projetos" # Used in the UI
    folder: "data/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Nome do projeto", name: "title", widget: "string"}
      - {label: "Data de publicação", name: "date", widget: "datetime"}
      - {label: "Descrição", name: "description", widget: "text"}
      - {label: "Imagens da galeria", name: "gallery", widget: "list", field: {label: "Imagem", name: "img", widget: "image"}}
      - {label: "Imagens do projeto", name: "project", widget: "list", field: {label: "Imagem", name: "img", widget: "image"}}