backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: "static/images" # Media files will be stored in the repo under src/images
public_folder: "/images"

collections:
  - name: "projetos" # Used in routes, e.g., /admin/collections/blog
    label: "Projetos" # Used in the UI
    folder: "data/projects"
    create: true
    fields:
      - {name: "type", widget: hidden, default: "project"}
      - {label: "Obs: Não faça o upload de imagens maiores que 4mb, use um otimizador de imagens se preciso (ex: http://www.imagesmaller.com/)", name: "instruções", widget: boolean, }
      - {label: "Título (não aparece no site)", name: "title", widget: string, required: true}
      - {label: "Data (usado para ordenar imagens na página)", name: "date", widget: "datetime", required: true}
      - {label: "Descrição geral (opcional)", name: "description", widget: "text", required: false}
      - label: "Imagens da Galeria"
        name: "gallery"
        widget: "list"
        required: false
        fields:
          - {label: "Imagem selecionada", name: "img", widget: "image", required: true}
          - {label: "Destaque (aumenta a largura da imagem na grid)", name: "featured", widget: "boolean", default: false, required: true}
          - {label: "Descrição (opcional e sobrescreve a descrição geral)", name: "description", widget: "text"}
      - label: "Imagens do projeto"
        name: "project"
        widget: "list"
        required: false
        fields:
          - {label: "Imagem selecionada", name: "img", widget: "image", required: true}
          - {label: "Destaque", name: "featured", widget: "boolean", default: false, required: true}
          - {label: "Descrição (opcional e sobrescreve a descrição do projeto)", name: "description", widget: "text"}
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Páginas do site" # Used in the UI
    files:
      - label: "Sobre"
        name: "sobre"
        file: "data/pages/Sobre.md"
        delete: false
        fields:
          - {name: "page", widget: hidden}
          - {name: "title", widget: hidden}
          - {label: "Imagem da capa", name: "heroImg", widget: "image", required: true}
          - {label: "Texto", name: "content", widget: "text", required: true}
      - label: "Contato"
        name: "contact"
        file: "data/pages/Contato.md"
        delete: false
        fields:
          - {name: "page", widget: hidden}
          - {label: "Imagem da capa", name: "heroImg", widget: "image", required: true}
          - {label: "Telefone", name: "phone", widget: "string", required: true}
          - {label: "Email", name: "email", widget: "string", required: true}
          - {label: "Endereço", name: "address", widget: "markdown", required: true}
          - {label: "Link para o instagram (opcional)", name: "instagramLink", widget: "string"}
          - {label: "Link para o facebook (opcional)", name: "facebookLink", widget: "string"}
          - {label: "Whatsapp no formato ddi+ddd+num sem espaço ex: 5511988887777 (opcional)", name: "whatsapp", widget: "string"}
